# Generated by Django 3.2.24 on 2024-04-27 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_alter_prescription_px_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_required',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
