# Generated by Django 3.2.24 on 2024-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_prescription_date_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_required',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
