# Generated by Django 3.2.24 on 2024-05-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_user_userprofile_user'),
        ('prescription', '0005_prescription_px_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='px_orders', to='profiles.userprofile'),
        ),
    ]
