# Generated by Django 3.2.24 on 2024-05-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_user_userprofile_user'),
        ('prescription', '0006_prescription_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_user', to='profiles.userprofile'),
        ),
    ]
