# Generated by Django 3.2.24 on 2024-05-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_auto_20240502_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user_profile',
        ),
    ]
