# Generated by Django 3.2.24 on 2024-04-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name_plural': 'Communication'},
        ),
    ]
