# Generated by Django 3.2.24 on 2024-04-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_communication_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communication',
            new_name='CommunicationType',
        ),
        migrations.AlterModelOptions(
            name='communicationtype',
            options={'verbose_name_plural': 'Communication Type'},
        ),
    ]
