# Generated by Django 3.2.24 on 2024-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
