# Generated by Django 3.2.24 on 2024-04-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240413_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationcontent',
            name='image',
            field=models.ImageField(default='phelans-logo-high-cropped.png', upload_to='uploads/'),
        ),
    ]
