# Generated by Django 3.2.24 on 2024-04-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productbundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbundle',
            options={'verbose_name_plural': 'Product Bundles'},
        ),
    ]
